apiVersion: v1
kind: Pod
metadata:
  name: echo
  labels:
    name: echo
  namespace: default
spec:
  containers:
  - name: echo
    image: echo:v2
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    name: echo
  namespace: default
spec:
  type: NodePort
  selector:
    name: echo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30062